### ISSUE TITLE
use-case: pool of pre-built clusters

### ISSUE THREAD

**Issue by errordeveloper** [isovalent/gke-test-cluster-operator#4]
Currently cluster provisioning is done on-demand, so it takes at least 5 minutes to obtain a cluster.
Since cluster configuration is based on well-known templates, and for testing purposes region and scale shouldn't matter, it should be possible to maintain a pool of cluster that had been pre-built and enable faster provisioning for CI job to run faster.

It should be possible to control pool size with based on business needs, e.g. scale up during business hours and scale down out-of-hours, and even a predictive model can be implement if so desired.

## TODOs

- [ ] design a basic `TestClusterPoolGKE` object
   - make it namespaced
   - initially it should be support only `type: static`, but may extend to e.g. `type: businessHours`
   - it should support subset of parameters that `TestClusterGKE` offers, e.g. location and scale shouldn't matter
   - it may need to provide options like scaling nodes on job assignment
- [ ] implement and test it
   - refactor how job is created, i.e. it will need to be done when cluster is take from a pool
- [ ] deploy it in CI
